"""Watcher framework — Sprint 3.6 Parts 2, 7 and 8.

A Watcher observes EVOLVING STATE (odds history, stat series, risk
ledgers, narrative features) on a schedule and produces Observations:
synthetic-signal-bearing trend inputs that flow through the SAME
TrendIntelligencePipeline real events use. No special path, no
duplicated detection logic — watchers assemble inputs; the existing
detectors decide.

The scheduler runs each watcher in its own isolated task with
configurable interval + jitter: a watcher failure never stops Atlas
and never blocks ingestion.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time
from dataclasses import dataclass, field
from typing import Protocol

from prometheus_client import Counter, Gauge, Histogram

from atlas.signal_engine import Signal
from atlas.trends.models import TrendInputs

logger = logging.getLogger(__name__)

ATLAS_WATCHER_RUNS_TOTAL = Counter(
    "atlas_watcher_runs_total",
    "Watcher observation passes executed.",
    ["watcher"],
)
ATLAS_WATCHER_FAILURES_TOTAL = Counter(
    "atlas_watcher_failures_total",
    "Watcher observation passes that raised.",
    ["watcher"],
)
ATLAS_WATCHER_DURATION_SECONDS = Histogram(
    "atlas_watcher_duration_seconds",
    "Seconds one watcher observation pass took.",
    ["watcher"],
)
ATLAS_SYNTHETIC_SIGNALS_TOTAL = Counter(
    "atlas_synthetic_signals_total",
    "Synthetic signals generated by the continuous observation layer.",
    ["watcher", "signal_type"],
)
ATLAS_WATCHER_CONFIG = Gauge(
    "atlas_watcher_config",
    "Effective continuous-observation configuration, one sample per "
    "parameter — lets dashboards/alerts see the thresholds a deployment "
    "is actually running with.",
    ["parameter"],
)


def export_watcher_config(**parameters: float) -> None:
    """Publish the effective watcher configuration as gauge samples."""
    for name, value in parameters.items():
        ATLAS_WATCHER_CONFIG.labels(parameter=name).set(float(value))


@dataclass(frozen=True, slots=True)
class Observation:
    """One synthetic observation: the trend inputs a watcher assembled
    from evolving state, carrying its synthetic signals. Fed into the
    standard trend pipeline by the sink."""

    inputs: TrendInputs
    signals: list[Signal] = field(default_factory=list)


class Watcher(Protocol):
    """The continuous observation contract."""

    def name(self) -> str: ...
    def enabled(self) -> bool: ...
    async def observe(self) -> list[Observation]: ...


class WatcherRegistry:
    """Startup registry — Atlas registers watchers here; the scheduler
    runs whatever is registered. Built for future expansion: adding a
    watcher is one Register call."""

    def __init__(self) -> None:
        self._watchers: list[Watcher] = []

    def register(self, watcher: Watcher) -> None:
        self._watchers.append(watcher)

    def watchers(self) -> list[Watcher]:
        return list(self._watchers)


class WatcherScheduler:
    """Runs every enabled watcher periodically, isolated.

    - per-watcher asyncio task (a slow watcher never delays another)
    - configurable base interval + absolute jitter (seconds)
    - watchdog metrics on every pass
    - graceful shutdown via stop()
    """

    def __init__(
        self,
        registry: WatcherRegistry,
        sink,  # ObservationSink — duck-typed to avoid import cycles
        *,
        interval_seconds: float = 30.0,
        jitter_seconds: float = 6.0,
    ) -> None:
        self._registry = registry
        self._sink = sink
        self._interval = max(1.0, interval_seconds)
        # Jitter can never exceed the interval (delay stays positive).
        self._jitter = min(max(jitter_seconds, 0.0), self._interval * 0.9)
        self._tasks: list[asyncio.Task] = []
        self._stopping = asyncio.Event()

    def start(self) -> None:
        for watcher in self._registry.watchers():
            task = asyncio.create_task(
                self._run_watcher(watcher),
                name=f"atlas-watcher-{watcher.name()}",
            )
            self._tasks.append(task)
        logger.info(
            "atlas_watchers_started",
            extra={"watchers": [w.name() for w in self._registry.watchers()]},
        )

    async def stop(self) -> None:
        self._stopping.set()
        for task in self._tasks:
            task.cancel()
        for task in self._tasks:
            try:
                await task
            except (asyncio.CancelledError, Exception):  # noqa: BLE001
                pass
        logger.info("atlas_watchers_stopped")

    async def run_once(self, watcher: Watcher) -> int:
        """One isolated observation pass. Returns observations fed.
        Exposed for tests + manual ops."""
        if not watcher.enabled():
            return 0
        started = time.perf_counter()
        ATLAS_WATCHER_RUNS_TOTAL.labels(watcher=watcher.name()).inc()
        try:
            observations = await watcher.observe()
        except Exception:  # noqa: BLE001 — watcher isolation
            ATLAS_WATCHER_FAILURES_TOTAL.labels(watcher=watcher.name()).inc()
            logger.exception(
                "atlas_watcher_failed", extra={"watcher": watcher.name()}
            )
            return 0
        finally:
            ATLAS_WATCHER_DURATION_SECONDS.labels(watcher=watcher.name()).observe(
                time.perf_counter() - started
            )
        fed = 0
        for obs in observations:
            for signal in obs.signals:
                ATLAS_SYNTHETIC_SIGNALS_TOTAL.labels(
                    watcher=watcher.name(), signal_type=signal.signal_type.value
                ).inc()
            try:
                await self._sink.process(obs)
                fed += 1
            except Exception:  # noqa: BLE001 — sink failure is isolated too
                ATLAS_WATCHER_FAILURES_TOTAL.labels(watcher=watcher.name()).inc()
                logger.exception(
                    "atlas_watcher_sink_failed", extra={"watcher": watcher.name()}
                )
        return fed

    async def _run_watcher(self, watcher: Watcher) -> None:
        while not self._stopping.is_set():
            await self.run_once(watcher)
            await asyncio.sleep(self._next_delay())

    def _next_delay(self) -> float:
        if self._jitter <= 0:
            return self._interval
        return self._interval + random.uniform(-self._jitter, self._jitter)


class ObservationSink:
    """Feeds observations into the standard trend pipeline — the exact
    path event-driven trends take. No special path."""

    def __init__(self, trends_pipeline) -> None:
        self._pipeline = trends_pipeline

    async def process(self, obs: Observation) -> None:
        await self._pipeline.process(obs.inputs)
