apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insight-sports-hub-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: insight-vault
    kind: ClusterSecretStore
  target:
    name: insight-sports-hub-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: insight/sports-hub
        property: database_url
