apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: insight
commonLabels:
  app.kubernetes.io/name: insight-sports-hub
  app.kubernetes.io/part-of: insight
  app.kubernetes.io/component: backend
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - external-secret.yaml
