"""Model registry tables.

The registry is the source of truth for which model artifact is loaded
for inference. Tables:

  * `atlas.model_versions`  — one row per trained artifact
  * `atlas.training_runs`   — log of training jobs (incl. failures)

Versions move through stages:
  staged → active → archived
The inference engine loads exactly the `active` row for each family.
Promotion is explicit and idempotent (POST `/v1/internal/models/promote`).
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone
from uuid import UUID, uuid4

from sqlalchemy import JSON, DateTime, Enum, Float, ForeignKey, Index, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

# migrations/sql/0003_create_odds_ticks.sql declares `payload` as JSONB
# (GIN-indexable, containment-queryable) — the plain generic JSON type
# below would silently drift from that on a real Postgres deployment.
# with_variant renders as JSONB on postgres, plain JSON on sqlite (JSONB
# has no sqlite compiler support at all — Base.metadata.create_all
# against the sqlite-backed test suite would hard-fail otherwise).
_JSONB_ON_POSTGRES = JSON().with_variant(JSONB, "postgresql")

from atlas.registry.base import Base


class ModelFamily(str, enum.Enum):
    anomaly = "anomaly"            # IsolationForest
    cluster = "cluster"            # KMeans (stable IDs)
    density = "density"            # HDBSCAN
    classifier = "classifier"      # XGBoost
    ranker = "ranker"              # LightGBM
    similarity = "similarity"      # historical nearest-neighbour index


class ModelStage(str, enum.Enum):
    staged = "staged"
    active = "active"
    archived = "archived"


class LabelSource(str, enum.Enum):
    """Where the training labels for this model version came from.

    Sprint 0 mandates "clear separation between candidate bot signals
    and confirmed events". Same rule applies to labels themselves:
    bootstrap-rule labels are a candidate signal, not ground truth,
    and the operator promoting a model must SEE that distinction.

    `none`              — model is unsupervised (anomaly, cluster, density)
    `bootstrap_rule`    — labels generated by the deterministic rule in
                          atlas.models.classifier.bootstrap_labels.
                          Models trained this way are essentially the
                          rule with XGBoost noise; treat as candidate
                          until refit with real labels.
    `historical_outcome` — labels derived from observed match outcomes
                          (the post-V1 path once enough history exists).
    `human_curated`     — labels assigned by an analyst.
    """

    none = "none"
    bootstrap_rule = "bootstrap_rule"
    historical_outcome = "historical_outcome"
    human_curated = "human_curated"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class ModelVersion(Base):
    __tablename__ = "model_versions"
    __table_args__ = ({"schema": "atlas"},)

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    family: Mapped[ModelFamily] = mapped_column(Enum(ModelFamily, name="atlas_family"))
    semver: Mapped[str] = mapped_column(String(32))
    stage: Mapped[ModelStage] = mapped_column(
        Enum(ModelStage, name="atlas_stage"), default=ModelStage.staged
    )
    artifact_path: Mapped[str] = mapped_column(String(512))
    feature_schema_version: Mapped[int] = mapped_column(Integer)
    train_metric: Mapped[float | None] = mapped_column(Float, nullable=True)
    feature_importance: Mapped[dict] = mapped_column(JSON, default=dict)
    notes: Mapped[str] = mapped_column(String(512), default="")
    # Sprint 0 — provenance of training labels. See LabelSource docstring.
    # Default `none` for unsupervised families; classifier/ranker set this
    # explicitly via the training pipeline.
    label_source: Mapped[LabelSource] = mapped_column(
        Enum(LabelSource, name="atlas_label_source"),
        default=LabelSource.none,
    )
    dataset_version: Mapped[str] = mapped_column(String(128), default="")
    historical_window: Mapped[dict] = mapped_column(JSON, default=dict)
    dataset_metadata: Mapped[dict] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    runs: Mapped[list[TrainingRun]] = relationship(
        "TrainingRun", back_populates="version", cascade="all,delete-orphan"
    )


class TrainingRun(Base):
    __tablename__ = "training_runs"
    __table_args__ = ({"schema": "atlas"},)

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    version_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("atlas.model_versions.id"), nullable=True
    )
    family: Mapped[ModelFamily] = mapped_column(Enum(ModelFamily, name="atlas_family"))
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    succeeded: Mapped[bool] = mapped_column(default=False)
    sample_count: Mapped[int] = mapped_column(Integer, default=0)
    feature_schema_version: Mapped[int] = mapped_column(Integer)
    metrics: Mapped[dict] = mapped_column(JSON, default=dict)
    error: Mapped[str] = mapped_column(String(2048), default="")

    version: Mapped[ModelVersion | None] = relationship(
        "ModelVersion", back_populates="runs"
    )


class OddsTickRow(Base):
    """One persisted odds snapshot — the first-class odds-history row.

    Every `match.odds` canonical event Atlas consumes is appended here
    as its own row; we DO NOT keep only the latest snapshot. The full
    temporal evolution of every (match, market, bookmaker) lane is
    reconstructable by ordering on `captured_at`.

    Idempotency: `canonical_event_id` is unique. Re-delivery of the
    same canonical event (consumer reclaim/replay) is a no-op insert,
    so history never double-counts a snapshot.
    """

    __tablename__ = "odds_ticks"
    __table_args__ = (
        # Name matches migrations/sql/0003_create_odds_ticks.sql exactly
        # — create_all() against an already-migrated Postgres (or a
        # second create_all() call anywhere) must not create a
        # redundant duplicate index under a different name.
        Index("ix_odds_ticks_match_market_captured", "match_id", "market", "captured_at"),
        {"schema": "atlas"},
    )

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    # The Hub's canonical event id — unique idempotency key.
    canonical_event_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), unique=True, index=True
    )
    provider: Mapped[str] = mapped_column(String(64))
    competition_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True), nullable=True
    )
    # Stable per-match grouping key (payload.match_id) — NOT the
    # snapshot-scoped canonical match_id.
    match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    market: Mapped[str] = mapped_column(String(32))
    bookmaker: Mapped[str] = mapped_column(String(64))
    home: Mapped[float | None] = mapped_column(Float, nullable=True)
    draw: Mapped[float | None] = mapped_column(Float, nullable=True)
    away: Mapped[float | None] = mapped_column(Float, nullable=True)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    # Full normalized payload — preserves outcomes for non-h2h markets
    # + any provider fields beyond the foundational home/draw/away.
    payload: Mapped[dict] = mapped_column(_JSONB_ON_POSTGRES, default=dict)
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class TeamStrengthStateRow(Base):
    """Global per-team rating state (Sprint ATLAS-SIM-A). Elo is not
    competition-scoped — a team carries one rating across competitions,
    same convention `HistoricalProjectionV3`'s in-memory `_elo` dict uses.
    """

    __tablename__ = "team_strength_state"
    __table_args__ = ({"schema": "atlas"},)

    team: Mapped[str] = mapped_column(String(128), primary_key=True)
    elo: Mapped[float] = mapped_column(Float, default=1500.0)
    venue_elo_home: Mapped[float] = mapped_column(Float, default=1500.0)
    venue_elo_away: Mapped[float] = mapped_column(Float, default=1500.0)
    # Rolling last-10 {gf, ga} results, most recent last.
    rolling_window: Mapped[list] = mapped_column(JSON, default=list)
    last_match_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class TeamStandingsStateRow(Base):
    """Per-(competition, season) standings — points/goal-difference are
    only meaningful within one competition's table."""

    __tablename__ = "team_standings_state"
    __table_args__ = (
        Index(
            "ix_team_standings_state_table",
            "competition", "season", "points", "goal_difference",
        ),
        {"schema": "atlas"},
    )

    competition: Mapped[str] = mapped_column(String(128), primary_key=True)
    season: Mapped[str] = mapped_column(String(32), primary_key=True)
    team: Mapped[str] = mapped_column(String(128), primary_key=True)
    points: Mapped[int] = mapped_column(Integer, default=0)
    goal_difference: Mapped[int] = mapped_column(Integer, default=0)
    matches_played: Mapped[int] = mapped_column(Integer, default=0)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class CompetitionSeasonStateRow(Base):
    """Per-(competition, season) league scoring rate — normalizes
    attack/defense strength relative to the league's own average."""

    __tablename__ = "competition_season_state"
    __table_args__ = ({"schema": "atlas"},)

    competition: Mapped[str] = mapped_column(String(128), primary_key=True)
    season: Mapped[str] = mapped_column(String(32), primary_key=True)
    goal_sum: Mapped[int] = mapped_column(Integer, default=0)
    team_match_count: Mapped[int] = mapped_column(Integer, default=0)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class HeadToHeadStateRow(Base):
    """Head-to-head counters, keyed by a CANONICALLY ORDERED team pair
    (team_a < team_b lexicographically) so a lookup is direction-agnostic;
    the caller maps team_a_wins/team_b_wins onto home/away at query time.
    """

    __tablename__ = "head_to_head_state"
    __table_args__ = ({"schema": "atlas"},)

    team_a: Mapped[str] = mapped_column(String(128), primary_key=True)
    team_b: Mapped[str] = mapped_column(String(128), primary_key=True)
    team_a_wins: Mapped[int] = mapped_column(Integer, default=0)
    team_b_wins: Mapped[int] = mapped_column(Integer, default=0)
    draws: Mapped[int] = mapped_column(Integer, default=0)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class StrengthProcessedMatchRow(Base):
    """Idempotency ledger for the strength-sync watcher: one row per
    Explorer match uid already folded into the state above. Same role
    `OddsTickRow.canonical_event_id` plays for the odds pipeline."""

    __tablename__ = "strength_processed_matches"
    __table_args__ = ({"schema": "atlas"},)

    match_uid: Mapped[str] = mapped_column(String(256), primary_key=True)
    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )


class CanonicalMatchRow(Base):
    """One canonical cross-provider match identity (Sprint 6.2).

    Resolved from (competition, home team, away team, kickoff) with a
    tolerance window. Provider-native ids are preserved in MatchAliasRow.
    """

    __tablename__ = "canonical_match"
    __table_args__ = (
        Index("ix_canonical_match_lookup", "competition_id", "home_team", "away_team"),
        {"schema": "atlas"},
    )

    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    competition_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    home_team: Mapped[str] = mapped_column(String(128), default="")
    away_team: Mapped[str] = mapped_column(String(128), default="")
    kickoff: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class MatchAliasRow(Base):
    """Provider-native match id -> canonical match id (Sprint 6.2).

    Provider ids are NEVER discarded - every observation stays traceable
    to its origin. Composite key (provider, external_id) is the fast path.
    """

    __tablename__ = "match_alias"
    __table_args__ = ({"schema": "atlas"},)

    provider: Mapped[str] = mapped_column(String(64), primary_key=True)
    external_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    linked_by: Mapped[str] = mapped_column(String(16), default="auto")
    linked_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class TrendEventRow(Base):
    """One detected trend - the durable trend history (Sprint 0, Trend
    Intelligence Foundation).

    Every trend the TrendEngine emits is appended here BEFORE stream
    publication, so the trend timeline is reconstructable and a failed
    publish is replayable. Keyed by trend_id (idempotent re-insert is a
    no-op at the engine level since trend_ids are mint-once).
    """

    __tablename__ = "trend_events"
    __table_args__ = (
        Index("ix_trend_events_match_type", "canonical_match_id", "trend_type", "detected_at"),
        {"schema": "atlas"},
    )

    trend_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    trend_type: Mapped[str] = mapped_column(String(48), index=True)
    category: Mapped[str] = mapped_column(String(16))
    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    competition_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    minute: Mapped[int | None] = mapped_column(Integer, nullable=True)
    strength: Mapped[float] = mapped_column(Float)
    confidence: Mapped[float] = mapped_column(Float)
    direction: Mapped[int] = mapped_column(Integer, default=0)
    evidence: Mapped[dict] = mapped_column(JSON, default=dict)
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    ingested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    # Sprint 1 - Trend Contract V1 fields (migration 0006).
    agent: Mapped[str] = mapped_column(String(24), default="")
    severity: Mapped[str] = mapped_column(String(12), default="")
    title: Mapped[str] = mapped_column(String(256), default="")
    summary: Mapped[str] = mapped_column(String(1024), default="")
    signals: Mapped[list] = mapped_column(JSON, default=list)
    chart_data: Mapped[dict] = mapped_column(JSON, default=dict)
    # Sprint 1.5 - Trend Contract V2 evaluation fields (migration 0009).
    publish_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    publication_tier: Mapped[str] = mapped_column(String(20), default="")
    lifecycle_state: Mapped[str] = mapped_column(String(16), default="")
    correlation_ids: Mapped[list] = mapped_column(JSON, default=list)
    # Sprint 2 - Contract V3 interpretation fields (migration 0010).
    meaning: Mapped[str] = mapped_column(String(64), default="")
    meaning_category: Mapped[str] = mapped_column(String(32), default="")
    meaning_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)


class TrendLifecycleRow(Base):
    """One evolving trend instance - the lifecycle state machine
    (Sprint 1.5). trend_events stays immutable; this row tracks how a
    detected pattern strengthened, weakened, confirmed, failed or
    expired over time, with full parallel histories for auditability.
    """

    __tablename__ = "trend_lifecycle"
    __table_args__ = (
        Index("ix_trend_lifecycle_match_state", "canonical_match_id", "current_state"),
        {"schema": "atlas"},
    )

    instance_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    trend_type: Mapped[str] = mapped_column(String(48), index=True)
    direction: Mapped[int] = mapped_column(Integer, default=0)
    current_state: Mapped[str] = mapped_column(String(16), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    trend_ids: Mapped[list] = mapped_column(JSON, default=list)
    strength_history: Mapped[list] = mapped_column(JSON, default=list)
    confidence_history: Mapped[list] = mapped_column(JSON, default=list)
    evidence_history: Mapped[list] = mapped_column(JSON, default=list)
    # Sprint 2 (A2) - ordered list of every state the instance entered.
    state_history: Mapped[list] = mapped_column(JSON, default=list)
    confirmed_by: Mapped[str | None] = mapped_column(String(64), nullable=True)
    failed_by: Mapped[str | None] = mapped_column(String(64), nullable=True)


class CorrelatedTrendRow(Base):
    """One correlated multi-trend detection (Sprint 1.5). Members are
    referenced by trend_id; the fusion trend the correlation also
    emits lives in trend_events like any other trend.
    """

    __tablename__ = "correlated_trends"
    __table_args__ = (
        Index("ix_correlated_trends_match", "canonical_match_id", "created_at"),
        {"schema": "atlas"},
    )

    correlation_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    correlation_type: Mapped[str] = mapped_column(String(32), index=True)
    member_trends: Mapped[list] = mapped_column(JSON, default=list)
    confidence: Mapped[float] = mapped_column(Float)
    strength: Mapped[float] = mapped_column(Float)
    evidence: Mapped[dict] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class PatternMemoryRow(Base):
    """Statistical pattern recurrence memory (Sprint 2, A3).

    One row per (competition, trend_type, direction) behaviour. Pure
    counters - occurrences and confirmed/failed outcomes from the trend
    lifecycle; the success rate is derived, never stored guesses.
    """

    __tablename__ = "pattern_memory"
    __table_args__ = (
        Index("ix_pattern_memory_competition", "competition_id"),
        {"schema": "atlas"},
    )

    pattern_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    competition_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    trend_type: Mapped[str] = mapped_column(String(48), index=True)
    direction: Mapped[int] = mapped_column(Integer, default=0)
    occurrences: Mapped[int] = mapped_column(Integer, default=0)
    confirmed: Mapped[int] = mapped_column(Integer, default=0)
    failed: Mapped[int] = mapped_column(Integer, default=0)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class TrendTimelineRow(Base):
    """One append-only trend timeline entry (Sprint 3.6).

    cluster_id is the trend lifecycle instance id - Atlas's story
    grouping unit. Rows are never updated or deleted: the timeline is
    the immutable narrative record a story leaves behind.
    """

    __tablename__ = "trend_timeline"
    __table_args__ = (
        Index("ix_trend_timeline_cluster", "cluster_id", "ts"),
        {"schema": "atlas"},
    )

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    cluster_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    ts: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    trend_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True))
    trend_type: Mapped[str] = mapped_column(String(48))
    lifecycle_state: Mapped[str] = mapped_column(String(16), default="")
    confidence: Mapped[float] = mapped_column(Float)
    strength: Mapped[float] = mapped_column(Float)
    summary: Mapped[str] = mapped_column(String(1024), default="")
    meaning: Mapped[str] = mapped_column(String(64), default="")


class StoryCoherenceRow(Base):
    """Latest story coherence per match (Sprint 3.6) - the agreement
    between market, match, risk and narrative dimensions. Upserted per
    computation; observability only.
    """

    __tablename__ = "story_coherence"
    __table_args__ = ({"schema": "atlas"},)

    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    score: Mapped[float] = mapped_column(Float)
    components: Mapped[dict] = mapped_column(JSON, default=dict)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class TrendOutcomeRow(Base):
    """One CLOSED trend lifecycle instance - the append-only outcome
    log the Intelligence Maturity layer (Sprint 1.5) aggregates over.

    Insert-once keyed by instance_id (replay-safe: re-recording the
    same closure is a no-op). Rows are never updated or deleted - every
    market-memory / historical-outcome / continuation profile is an
    auditable aggregate over this log.
    """

    __tablename__ = "trend_outcomes"
    __table_args__ = (
        Index("ix_trend_outcomes_type_comp", "trend_type", "competition_id"),
        Index("ix_trend_outcomes_closed", "closed_at"),
        {"schema": "atlas"},
    )

    instance_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    canonical_match_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    competition_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    trend_type: Mapped[str] = mapped_column(String(48), index=True)
    direction: Mapped[int] = mapped_column(Integer, default=0)
    # confirmed | failed | expired (TrendLifecycleState terminal values).
    outcome: Mapped[str] = mapped_column(String(16), index=True)
    duration_seconds: Mapped[float] = mapped_column(Float, default=0.0)
    avg_confidence: Mapped[float] = mapped_column(Float, default=0.0)
    avg_strength: Mapped[float] = mapped_column(Float, default=0.0)
    observation_count: Mapped[int] = mapped_column(Integer, default=0)
    home_team: Mapped[str] = mapped_column(String(128), default="")
    away_team: Mapped[str] = mapped_column(String(128), default="")
    closed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class CompetitionRegimeRow(Base):
    """One competition regime classification (Sprint 1.5) - append-only
    history so regime CHANGES are first-class, auditable events. The
    latest row per competition is the current regime.
    """

    __tablename__ = "competition_regimes"
    __table_args__ = (
        Index("ix_competition_regimes_comp", "competition_id", "computed_at"),
        {"schema": "atlas"},
    )

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=uuid4)
    competition_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), index=True)
    regime: Mapped[str] = mapped_column(String(24))
    # The CompetitionProfile snapshot that produced this classification.
    profile: Mapped[dict] = mapped_column(JSON, default=dict)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
