"""Atlas intelligence package.

The legacy Sprint 6.2 event pipeline remains available.  ATLAS-INTEL-A adds
the side-effect-free canonical domain language used by future providers.

Importing this package does not instantiate providers, models, storage, or
runtime consumers.
"""

from atlas.intelligence.contracts import (
    AtlasIntelligenceReport,
    BehaviorPattern,
    BehaviorType,
    Evidence,
    EvidenceType,
    HistoricalOutcomeDistribution,
    ConfidenceExplanation,
    ConflictInsight,
    IntelligenceEdge,
    IntelligenceEdgeType,
    IntelligenceGraph,
    IntelligenceNode,
    IntelligenceNodeType,
    IntelligenceSignal,
    MarketInsight,
    MarketMovement,
    MarketMovementDirection,
    PatternHistory,
    ReasoningInsight,
    ReasoningStatement,
    RegimeInsight,
    RegimeType,
    SignalDependencyEdge,
    SignalLifecycleStatus,
    SignalState,
    SignalStateSummary,
    SignalType,
    SimilarityInsight,
    SimilarMatch,
    TrendDirection,
    TrendInsight,
    UncertaintyInsight,
    UncertaintyExplanation,
)
from atlas.intelligence.interfaces import (
    EvidenceProvider,
    MarketProvider,
    RegimeProvider,
    SignalProvider,
    SimilarityProvider,
    TrendProvider,
)
from atlas.intelligence.report_builder import HistoricalIntelligenceReportBuilder
from atlas.intelligence.orchestrator import (
    AtlasIntelligenceOrchestrator,
    AtlasRuntimeContext,
    RuntimeExecutionTrace,
    RuntimeOdds,
)
from atlas.intelligence.reasoning_engine import (
    DeterministicReasoningEngine,
    ReasoningResult,
)
from atlas.intelligence.similarity_engine import (
    HistoricalMemory,
    MatchSimilarityProfile,
    SimilarityEngine,
)
from atlas.intelligence.kernel import (
    INTELLIGENCE_SCHEMA_VERSION,
    Coverage,
    EvidenceID,
    EvidenceWindow,
    InsightID,
    IntelligenceContext,
    IntelligenceMetadata,
    RegimeID,
    SignalID,
    SimilarityID,
    TrendID,
)
from atlas.intelligence.pipeline import IntelligencePipeline, IntelligenceResult

__all__ = [
    "INTELLIGENCE_SCHEMA_VERSION",
    "AtlasIntelligenceReport",
    "BehaviorPattern",
    "BehaviorType",
    "ConfidenceExplanation",
    "ConflictInsight",
    "Coverage",
    "Evidence",
    "EvidenceID",
    "EvidenceType",
    "EvidenceProvider",
    "EvidenceWindow",
    "HistoricalOutcomeDistribution",
    "HistoricalIntelligenceReportBuilder",
    "AtlasIntelligenceOrchestrator",
    "AtlasRuntimeContext",
    "HistoricalMemory",
    "IntelligenceEdge",
    "IntelligenceEdgeType",
    "IntelligenceGraph",
    "IntelligenceNode",
    "IntelligenceNodeType",
    "InsightID",
    "IntelligenceContext",
    "IntelligenceMetadata",
    "IntelligencePipeline",
    "IntelligenceResult",
    "IntelligenceSignal",
    "MarketInsight",
    "MarketMovement",
    "MarketMovementDirection",
    "PatternHistory",
    "ReasoningInsight",
    "ReasoningResult",
    "ReasoningStatement",
    "MarketProvider",
    "MatchSimilarityProfile",
    "RegimeID",
    "RegimeInsight",
    "RegimeProvider",
    "RegimeType",
    "RuntimeExecutionTrace",
    "RuntimeOdds",
    "DeterministicReasoningEngine",
    "SignalDependencyEdge",
    "SignalID",
    "SignalLifecycleStatus",
    "SignalProvider",
    "SignalState",
    "SignalStateSummary",
    "SignalType",
    "SimilarityID",
    "SimilarityEngine",
    "SimilarityInsight",
    "SimilarityProvider",
    "SimilarMatch",
    "TrendDirection",
    "TrendID",
    "TrendInsight",
    "TrendProvider",
    "UncertaintyInsight",
    "UncertaintyExplanation",
]
