"""Signal generation from classified events.

Single-event signals (a goal, a red card, an odds shift) are produced
here directly from the event + its impact classification. Aggregated
signals (PRESSURE_SPIKE, MOMENTUM_SWING from sustained patterns) are
produced by the Event Aggregation engine, which reuses this Signal
model.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from prometheus_client import Counter

from atlas.event_impact import Impact, ImpactClassification
from atlas.signal_engine.models import Signal, SignalType

SIGNALS_GENERATED_TOTAL = Counter(
    "signals_generated_total",
    "Signals generated by Atlas, by type and source path.",
    ["signal_type", "source"],
)

# Event category → single-event signal type. Categories without a direct
# signal (fixture, standings, routine play) produce no signal here.
CATEGORY_TO_SIGNAL: dict[str, SignalType] = {
    "goal": SignalType.GOAL,
    "red_card": SignalType.RED_CARD,
    "penalty": SignalType.PENALTY,
    "injury": SignalType.INJURY,
    "substitution": SignalType.LINEUP_CHANGE,
    "key_substitution": SignalType.LINEUP_CHANGE,
    "odds": SignalType.ODDS_SHIFT,
    "match_suspended": SignalType.MATCH_SUSPENDED,
    "match_resumed": SignalType.MATCH_RESUMED,
}

# Per-impact confidence weight (descriptive certainty, not probability).
_IMPACT_WEIGHT = {
    Impact.LOW: 0.40,
    Impact.MEDIUM: 0.60,
    Impact.HIGH: 0.80,
    Impact.CRITICAL: 0.95,
}


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class SignalEngine:
    """Generates single-event signals from classified canonical events."""

    def __init__(self, *, mapping: dict[str, SignalType] | None = None) -> None:
        self._mapping = dict(mapping) if mapping is not None else dict(CATEGORY_TO_SIGNAL)

    def generate(
        self,
        *,
        event: dict[str, Any],
        classification: ImpactClassification,
        canonical_match_id: UUID,
        now: datetime | None = None,
    ) -> list[Signal]:
        signal_type = self._mapping.get(classification.category)
        if signal_type is None:
            return []
        signal = Signal(
            signal_type=signal_type,
            canonical_match_id=canonical_match_id,
            confidence=self._confidence(event, classification),
            impact=classification.impact.label,
            evidence_count=1,
            created_at=now or _utcnow(),
            metadata={
                "event_id": event.get("event_id"),
                "category": classification.category,
                "competition_id": event.get("competition_id"),
            },
        )
        SIGNALS_GENERATED_TOTAL.labels(
            signal_type=signal_type.value, source="event"
        ).inc()
        return [signal]

    def _confidence(
        self, event: dict[str, Any], classification: ImpactClassification
    ) -> float:
        source = event.get("source") or {}
        src_conf = source.get("confidence", 0.7)
        try:
            src_conf = float(src_conf)
        except (TypeError, ValueError):
            src_conf = 0.7
        src_conf = min(max(src_conf, 0.0), 1.0)
        impact_weight = _IMPACT_WEIGHT.get(classification.impact, 0.5)
        return round(min(1.0, 0.5 * src_conf + 0.5 * impact_weight), 4)
