"""Signal model + taxonomy."""

from __future__ import annotations

import enum
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SignalOrigin(str, enum.Enum):
    """Where a signal came from (Sprint 3.6).

    `event`     — derived from a canonical event Atlas consumed.
    `synthetic` — generated by the continuous observation layer
                  (watchers) from evolving state, with no triggering
                  event. Synthetic signals flow through the SAME
                  pipeline as event signals — no special path.
    """

    event = "event"
    synthetic = "synthetic"


class SignalType(str, enum.Enum):
    GOAL = "GOAL"
    RED_CARD = "RED_CARD"
    PENALTY = "PENALTY"
    INJURY = "INJURY"
    LINEUP_CHANGE = "LINEUP_CHANGE"
    ODDS_SHIFT = "ODDS_SHIFT"
    MATCH_SUSPENDED = "MATCH_SUSPENDED"
    MATCH_RESUMED = "MATCH_RESUMED"
    PRESSURE_SPIKE = "PRESSURE_SPIKE"
    MOMENTUM_SWING = "MOMENTUM_SWING"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Signal(BaseModel):
    """An intelligence signal keyed on the canonical match identity.

    `impact` is the Impact tier label (LOW/MEDIUM/HIGH/CRITICAL).
    `evidence_count` is 1 for single-event signals and >1 for signals
    produced by aggregating several events.
    """

    model_config = ConfigDict(frozen=True)

    signal_type: SignalType
    canonical_match_id: UUID
    confidence: float = Field(ge=0.0, le=1.0)
    impact: str
    evidence_count: int = Field(default=1, ge=1)
    # Sprint 3.6 — every signal declares its origin.
    origin: SignalOrigin = SignalOrigin.event
    created_at: datetime = Field(default_factory=_utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)
