// Club Registry — Azteca side of the platform's canonical football
// identity layer. Loads the bundled `assets/clubs/logo_manifest.json`
// (generated by scripts/club_logo_crawler) and resolves any name /
// short code / alias to a stable club_id + a BUNDLED logo asset.
//
// No runtime logo API: every crest ships in the app under
// assets/clubs/<club_id>.png. Resolution is canonical, e.g.
//   "Manchester City", "Man City", "Manchester City FC" → manchester_city
import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

class Club {
  const Club({
    required this.clubId,
    required this.name,
    required this.shortName,
    required this.country,
    required this.logoPath,
  });

  final String clubId;
  final String name;
  final String shortName;
  final String country;
  final String logoPath; // "/clubs/<id>.png" (canonical)

  /// Bundled Flutter asset path for the crest.
  String get logoAsset =>
      logoPath.startsWith('assets/') ? logoPath : 'assets/clubs/$clubId.png';
}

class ClubRegistry {
  ClubRegistry._();
  static final ClubRegistry instance = ClubRegistry._();

  static const String _assetPath = 'assets/clubs/logo_manifest.json';

  final Map<String, Club> _byId = {};
  final Map<String, String> _index = {}; // normalized query -> club_id
  bool _loaded = false;

  bool get isLoaded => _loaded;
  String version = '';

  /// Loads + indexes the bundled registry. Idempotent; call once at
  /// boot. Safe to call before use — until loaded, [lookup] returns null
  /// (badge falls back to initials, never crashes).
  Future<void> load() async {
    if (_loaded) return;
    final raw = await rootBundle.loadString(_assetPath);
    ingest(raw);
  }

  /// Parse + index a registry JSON string (also the test seam).
  void ingest(String raw) {
    final decoded = jsonDecode(raw);
    final List<dynamic> entries;
    if (decoded
        case {'clubs': final List<dynamic> clubs, 'version': final Object? v}) {
      version = (v ?? '').toString();
      entries = clubs;
    } else if (decoded case final List<dynamic> list) {
      version = 'logo_manifest';
      entries = list;
    } else {
      entries = const <dynamic>[];
    }
    for (final entry in entries) {
      final j = entry as Map<String, dynamic>;
      final club = Club(
        clubId: (j['club_id'] ?? '').toString(),
        name: (j['name'] ?? '').toString(),
        shortName: (j['short_name'] ?? j['name'] ?? '').toString(),
        country: (j['country'] ?? '').toString(),
        logoPath: (j['logo_path'] ?? j['file'] ?? '').toString(),
      );
      if (club.clubId.isEmpty) continue;
      _byId[club.clubId] = club;
      _index[_normalize(club.clubId)] = club.clubId;
      _index[_normalize(club.name)] = club.clubId;
      _index[_normalize(club.shortName)] = club.clubId;
      for (final alias in _derivedAliases(club)) {
        _index[_normalize(alias)] = club.clubId;
      }
      for (final a in (j['aliases'] as List? ?? const [])) {
        _index[_normalize(a.toString())] = club.clubId;
      }
    }
    _loaded = true;
  }

  /// Canonical club_id for any name/short/alias, or null.
  String? resolve(String query) {
    if (query.isEmpty) return null;
    final normalized = _normalize(query);
    return _index[normalized] ??
        _index[_normalize(
          query.replaceAll(RegExp(r'\s+(fc|cf)$', caseSensitive: false), ''),
        )] ??
        _index[_normalize(
          query.replaceAll(RegExp(r'^(cr|ac|as)\s+', caseSensitive: false), ''),
        )];
  }

  Club? byId(String clubId) => _byId[clubId];

  /// One-step resolve: query → full club, or null.
  Club? lookup(String query) {
    final id = resolve(query);
    return id == null ? null : _byId[id];
  }

  Iterable<String> _derivedAliases(Club club) sync* {
    final withoutSuffix = club.name
        .replaceAll(RegExp(r'\s+(fc|cf)$', caseSensitive: false), '')
        .trim();
    final withoutPrefix = withoutSuffix
        .replaceAll(RegExp(r'^(cr|ac|as)\s+', caseSensitive: false), '')
        .trim();
    if (withoutSuffix != club.name) yield withoutSuffix;
    if (withoutPrefix != withoutSuffix) yield withoutPrefix;

    switch (club.clubId) {
      case 'manchester_city':
        yield 'Man City';
        yield 'MCI';
      case 'flamengo':
        yield 'CR Flamengo';
      case 'real_madrid':
        yield 'Real Madrid CF';
    }
  }

  int get count => _byId.length;

  // Case-fold, strip accents + non-alphanumerics so "Atlético-MG",
  // "atletico mg" and "AtleticoMG" collide (mirrors the Go resolver).
  static String _normalize(String s) {
    final lower = s.trim().toLowerCase();
    final buf = StringBuffer();
    for (final ch in lower.split('')) {
      final folded = _accents[ch] ?? ch;
      final code = folded.codeUnitAt(0);
      final isDigit = code >= 0x30 && code <= 0x39;
      final isAlpha = code >= 0x61 && code <= 0x7a;
      if (isDigit || isAlpha) buf.write(folded);
    }
    return buf.toString();
  }

  static const Map<String, String> _accents = {
    'á': 'a',
    'à': 'a',
    'â': 'a',
    'ã': 'a',
    'ä': 'a',
    'é': 'e',
    'è': 'e',
    'ê': 'e',
    'ë': 'e',
    'í': 'i',
    'ì': 'i',
    'î': 'i',
    'ï': 'i',
    'ó': 'o',
    'ò': 'o',
    'ô': 'o',
    'õ': 'o',
    'ö': 'o',
    'ú': 'u',
    'ù': 'u',
    'û': 'u',
    'ü': 'u',
    'ç': 'c',
    'ñ': 'n',
  };
}
