"""TrendEngine — composes the isolated named engines (Sprint 1).

Runs every registered engine over one tick's correlated inputs, then
applies a per-(match, trend_type) cooldown so the same developing trend
doesn't re-emit on every event. Engines fail independently (each
isolates its own detectors); the composer never raises.

Backwards compatibility: constructing with a bare detector list wraps
it in a single anonymous engine — the Sprint 0 surface still works.
"""

from __future__ import annotations

import logging
import time

from prometheus_client import Counter, Histogram

from atlas.event_aggregation.store import AggregationStore, now_seconds
from atlas.trends.engines import BaseTrendEngine, TrendDetector, default_engines
from atlas.trends.models import Trend, TrendInputs

logger = logging.getLogger(__name__)

# Evidence keys that identify WHICH subject a trend is about, for
# detectors that legitimately emit several trends of the SAME type in
# one tick (MarketAnomalyDetector: one per outlier bookmaker;
# MetaTrendDetector: one per team). Without a discriminator the cooldown
# key `trend:{match}:{type}` let only the first one through and silently
# dropped the rest into trends_suppressed_total — indistinguishable from
# the intended "same trend re-firing" suppression, and with no record of
# which subject was lost. Order is fixed so the key is deterministic.
_COOLDOWN_SUBJECT_KEYS: tuple[str, ...] = ("bookmaker", "team")


def _cooldown_key(trend: Trend) -> str:
    base = f"trend:{trend.canonical_match_id}:{trend.trend_type.value}"
    for key in _COOLDOWN_SUBJECT_KEYS:
        subject = trend.evidence.get(key)
        if subject:
            return f"{base}:{subject}"
    return base

TRENDS_GENERATED_TOTAL = Counter(
    "trends_generated_total",
    "Trends generated by the Atlas trend engine.",
    ["trend_type", "category", "agent"],
)
TRENDS_SUPPRESSED_TOTAL = Counter(
    "trends_suppressed_total",
    "Trends suppressed by the per-(match, type) cooldown.",
    ["trend_type"],
)
TREND_DETECTION_LATENCY_SECONDS = Histogram(
    "trend_detection_latency_seconds",
    "Seconds spent running the full trend engine set over one tick.",
)


def default_detectors() -> list[TrendDetector]:
    """Flattened default detector set (Sprint 0 compatibility surface;
    the engine-grouped form in atlas/trends/engines.py is canonical)."""
    out: list[TrendDetector] = []
    for engine in default_engines():
        out.extend(engine._detectors)  # noqa: SLF001 — same package
    return out


class TrendEngine:
    def __init__(
        self,
        detectors: list[TrendDetector] | None = None,
        *,
        engines: list[BaseTrendEngine] | None = None,
        cooldown_store: AggregationStore | None = None,
        cooldown_seconds: int = 120,
    ) -> None:
        if engines is not None and detectors is not None:
            raise ValueError("pass either detectors or engines, not both")
        if detectors is not None:
            self._engines = [BaseTrendEngine("custom", detectors)]
        elif engines is not None:
            self._engines = engines
        else:
            self._engines = default_engines()
        self._cooldown = cooldown_store
        self._cooldown_seconds = cooldown_seconds

    @property
    def engines(self) -> list[BaseTrendEngine]:
        return list(self._engines)

    async def detect(self, inputs: TrendInputs) -> list[Trend]:
        """Run every engine; apply the cooldown; return validated trends
        ready for persist + publish. Never raises."""
        started = time.perf_counter()
        candidates: list[Trend] = []
        for engine in self._engines:
            candidates.extend(engine.detect(inputs))

        kept: list[Trend] = []
        for trend in candidates:
            if self._cooldown is not None:
                key = _cooldown_key(trend)
                try:
                    allowed = await self._cooldown.allow_fire(
                        key, now_seconds(), self._cooldown_seconds
                    )
                except Exception:
                    # FAIL-OPEN. This method's contract is "Never raises"
                    # and BaseTrendEngine already isolates detector
                    # failures — but the cooldown call (Redis in
                    # production) sat outside any try, so a transient
                    # Redis blip propagated out of detect(), up through
                    # pipeline.process(), and killed the entire tick:
                    # lifecycle, persistence and publication of trends
                    # that had ALREADY been detected. Letting the trend
                    # through on a cooldown outage risks a duplicate
                    # emission; swallowing the tick loses real
                    # intelligence. Duplicates are the cheaper failure.
                    logger.warning(
                        "trend_cooldown_unavailable_failing_open",
                        extra={"trend_type": trend.trend_type.value, "key": key},
                        exc_info=True,
                    )
                    allowed = True
                if not allowed:
                    TRENDS_SUPPRESSED_TOTAL.labels(
                        trend_type=trend.trend_type.value
                    ).inc()
                    continue
            TRENDS_GENERATED_TOTAL.labels(
                trend_type=trend.trend_type.value,
                category=trend.category.value,
                agent=trend.agent or "custom",
            ).inc()
            kept.append(trend)
        TREND_DETECTION_LATENCY_SECONDS.observe(time.perf_counter() - started)
        return kept
