"""TrendEngine — composes the isolated named engines (Sprint 1).

Runs every registered engine over one tick's correlated inputs, then
applies a per-(match, trend_type) cooldown so the same developing trend
doesn't re-emit on every event. Engines fail independently (each
isolates its own detectors); the composer never raises.

Backwards compatibility: constructing with a bare detector list wraps
it in a single anonymous engine — the Sprint 0 surface still works.
"""

from __future__ import annotations

import time

from prometheus_client import Counter, Histogram

from atlas.event_aggregation.store import AggregationStore, now_seconds
from atlas.trends.engines import BaseTrendEngine, TrendDetector, default_engines
from atlas.trends.models import Trend, TrendInputs

TRENDS_GENERATED_TOTAL = Counter(
    "trends_generated_total",
    "Trends generated by the Atlas trend engine.",
    ["trend_type", "category", "agent"],
)
TRENDS_SUPPRESSED_TOTAL = Counter(
    "trends_suppressed_total",
    "Trends suppressed by the per-(match, type) cooldown.",
    ["trend_type"],
)
TREND_DETECTION_LATENCY_SECONDS = Histogram(
    "trend_detection_latency_seconds",
    "Seconds spent running the full trend engine set over one tick.",
)


def default_detectors() -> list[TrendDetector]:
    """Flattened default detector set (Sprint 0 compatibility surface;
    the engine-grouped form in atlas/trends/engines.py is canonical)."""
    out: list[TrendDetector] = []
    for engine in default_engines():
        out.extend(engine._detectors)  # noqa: SLF001 — same package
    return out


class TrendEngine:
    def __init__(
        self,
        detectors: list[TrendDetector] | None = None,
        *,
        engines: list[BaseTrendEngine] | None = None,
        cooldown_store: AggregationStore | None = None,
        cooldown_seconds: int = 120,
    ) -> None:
        if engines is not None and detectors is not None:
            raise ValueError("pass either detectors or engines, not both")
        if detectors is not None:
            self._engines = [BaseTrendEngine("custom", detectors)]
        elif engines is not None:
            self._engines = engines
        else:
            self._engines = default_engines()
        self._cooldown = cooldown_store
        self._cooldown_seconds = cooldown_seconds

    @property
    def engines(self) -> list[BaseTrendEngine]:
        return list(self._engines)

    async def detect(self, inputs: TrendInputs) -> list[Trend]:
        """Run every engine; apply the cooldown; return validated trends
        ready for persist + publish. Never raises."""
        started = time.perf_counter()
        candidates: list[Trend] = []
        for engine in self._engines:
            candidates.extend(engine.detect(inputs))

        kept: list[Trend] = []
        for trend in candidates:
            if self._cooldown is not None:
                key = f"trend:{trend.canonical_match_id}:{trend.trend_type.value}"
                allowed = await self._cooldown.allow_fire(
                    key, now_seconds(), self._cooldown_seconds
                )
                if not allowed:
                    TRENDS_SUPPRESSED_TOTAL.labels(
                        trend_type=trend.trend_type.value
                    ).inc()
                    continue
            TRENDS_GENERATED_TOTAL.labels(
                trend_type=trend.trend_type.value,
                category=trend.category.value,
                agent=trend.agent or "custom",
            ).inc()
            kept.append(trend)
        TREND_DETECTION_LATENCY_SECONDS.observe(time.perf_counter() - started)
        return kept
